# Generated by Django 2.2.2 on 2019-07-06 18:37

from django.db import migrations, models
import django.db.models.deletion
import k2_core.mixins.domain
import k2_core.mixins.field
import k2_core.mixins.model
import k2_core.mixins.sub_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('k2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('title', models.CharField(max_length=90, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            bases=(models.Model, k2_core.mixins.domain.DomainMixin),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='k2_app.Member')),
                ('max_length', models.IntegerField(blank=True, default=0, null=True, verbose_name='Max Length')),
                ('required', models.NullBooleanField(default=False, verbose_name='Required')),
                ('default_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Default value')),
                ('field_type', models.CharField(choices=[('BLN', 'Boolean'), ('NBL', 'Null boolean'), ('STR', 'String'), ('DTE', 'Date'), ('DTM', 'Date time'), ('DEC', 'Decimal'), ('EML', 'Email'), ('IMG', 'Image'), ('INT', 'Integer'), ('PIN', 'Positive integer'), ('TXT', 'Memo'), ('TME', 'Time'), ('URL', 'URL'), ('LKD', 'Linked field'), ('SBT', 'Sub type')], default='STR', max_length=3, verbose_name='Field Type')),
                ('on_delete_type', models.CharField(blank=True, choices=[('CAS', 'Cascade'), ('PRO', 'Protect'), ('NUL', 'Blank')], default='CAS', max_length=3, null=True, verbose_name='On delete')),
            ],
            bases=('k2_app.member', k2_core.mixins.field.FieldMixin),
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('value', models.CharField(max_length=3, verbose_name='Value')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='k2_domain.Field')),
            ],
            bases=(models.Model, k2_core.mixins.sub_type.SubTypeMixin),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('basetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='k2_app.BaseType')),
                ('title', models.CharField(max_length=90, verbose_name='Title')),
                ('p_title', models.CharField(blank=True, max_length=90, null=True, verbose_name='Plural title')),
                ('admin_model', models.BooleanField(blank=True, default=False, null=True, verbose_name='Admin Model')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='k2_domain.Domain')),
            ],
            bases=('k2_app.basetype', k2_core.mixins.model.ModelMixin),
        ),
    ]
