# Generated by Django 2.2.2 on 2019-06-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k2_domain', '0001_added_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('title', models.CharField(max_length=90, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='k2_domain.Domain')),
            ],
        ),
    ]
