# Generated by Django 2.2.2 on 2019-06-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k2_domain', '0002_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='admin_model',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Admin Model'),
        ),
    ]
