# Generated by Django 2.2.2 on 2019-06-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k2_domain', '0005_Added__Field_extends_Member'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='default_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Default value'),
        ),
        migrations.AddField(
            model_name='field',
            name='max_length',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Max Length'),
        ),
        migrations.AddField(
            model_name='field',
            name='required',
            field=models.NullBooleanField(default=False, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('BLN', 'Boolean'), ('NBL', 'Null boolean'), ('STR', 'String'), ('DTE', 'Date'), ('DTM', 'Date time'), ('DEC', 'Decimal'), ('EML', 'Email'), ('IMG', 'Image'), ('INT', 'Integer'), ('PIN', 'Positive integer'), ('TXT', 'Memo'), ('TME', 'Time'), ('URL', 'URL')], default='STR', max_length=3, verbose_name='Field Type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='data_type',
            field=models.CharField(choices=[('INT', 'Integer'), ('FLT', 'Float'), ('STR', 'String'), ('BLN', 'Boolean'), ('DTE', 'Date'), ('OBJ', 'Object')], default='STR', max_length=3, verbose_name='Data Type'),
        ),
    ]
