# Generated by Django 2.2.2 on 2019-06-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k2_domain', '0006_Added__Field_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='p_title',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Plural title'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('BLN', 'Boolean'), ('NBL', 'Null boolean'), ('STR', 'String'), ('DTE', 'Date'), ('DTM', 'Date time'), ('DEC', 'Decimal'), ('EML', 'Email'), ('IMG', 'Image'), ('INT', 'Integer'), ('PIN', 'Positive integer'), ('TXT', 'Memo'), ('TME', 'Time'), ('URL', 'URL'), ('FKY', 'Foreign key')], default='STR', max_length=3, verbose_name='Field Type'),
        ),
    ]
