# Generated by Django 2.2.2 on 2019-06-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k2_domain', '0007_Added_plural_title_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='on_delete_type',
            field=models.CharField(blank=True, choices=[('CAS', 'Cascade'), ('PRO', 'Protect'), ('NUL', 'Blank')], default='CAS', max_length=3, null=True, verbose_name='On delete'),
        ),
    ]
