# Generated by Django 2.2.2 on 2019-06-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k2_domain', '0008_Added_Field__on_delete_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('BLN', 'Boolean'), ('NBL', 'Null boolean'), ('STR', 'String'), ('DTE', 'Date'), ('DTM', 'Date time'), ('DEC', 'Decimal'), ('EML', 'Email'), ('IMG', 'Image'), ('INT', 'Integer'), ('PIN', 'Positive integer'), ('TXT', 'Memo'), ('TME', 'Time'), ('URL', 'URL'), ('LKD', 'Linked field'), ('SBT', 'Sub type')], default='STR', max_length=3, verbose_name='Field Type'),
        ),
    ]
