# Generated by Django 2.2.2 on 2019-06-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k2_domain', '0009_Added_SubType'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3, verbose_name='Value')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='k2_domain.Field')),
            ],
        ),
    ]
