# Generated by Django 2.2.2 on 2019-06-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('title', models.CharField(max_length=90, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_domains', to='k2_app.Application')),
            ],
        ),
    ]
