# Generated by Django 2.2.2 on 2019-07-06 17:18

from django.db import migrations, models
import django.db.models.deletion
import k2_core.mixins.application
import k2_core.mixins.application_domain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('k2_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=90)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, k2_core.mixins.application.ApplicationMixin),
        ),
        migrations.CreateModel(
            name='ApplicationDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_domains', to='k2_app.Application')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k2_domain.Domain')),
            ],
            bases=(models.Model, k2_core.mixins.application_domain.ApplicationDomainMixin),
        ),
    ]
