# Generated by Django 2.2.2 on 2019-07-08 20:39

from django.db import migrations, models
import django.db.models.deletion
import k2_core.mixins.clazz


class Migration(migrations.Migration):

    dependencies = [
        ('k2_app', '0002_auto_20190706_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('basetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='k2_app.BaseType')),
                ('foo', models.CharField(max_length=50, null=True, verbose_name='Foo')),
            ],
            bases=('k2_app.basetype', k2_core.mixins.clazz.ClazzMixin),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('FLD', 'Field'), ('EXP', 'Expression'), ('MTH', 'Method'), ('LST', 'List'), ('CLS', 'Class')], default='FLD', max_length=3, null=True, verbose_name='Member Type'),
        ),
        migrations.AddField(
            model_name='member',
            name='clazz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='k2_app.Clazz', verbose_name='Class'),
        ),
    ]
